"""site-calc-operational: plan a battery or CHP site's day from your own forecasts.

Two calls per delivery day: :meth:`OperationalClient.plan_reservation` before
the reservation gate, :meth:`OperationalClient.plan_day_ahead` before the
day-ahead gate. Everything is typed; see :mod:`site_calc_operational.models`.
"""

__version__ = "0.4.0"

from site_calc_operational.client import (
    API_KEY_PREFIX,
    DEFAULT_TIMEOUT_SECONDS,
    BusyRetry,
    OperationalClient,
)
from site_calc_operational.exceptions import (
    AuthenticationError,
    BusyError,
    CancelledError,
    DayNotPlannableError,
    IdempotencyConflictError,
    InfeasibleError,
    NotFoundError,
    OperationalError,
    OperationalTimeoutError,
    RequestTooLargeError,
    ServerError,
    TransportError,
    UnboundedError,
    ValidationError,
)
from site_calc_operational.models import (
    BLOCKS_PER_DAY,
    CHP,
    PRICE_TAKER_BUY_EUR_PER_MWH,
    PRICE_TAKER_SELL_EUR_PER_MWH,
    QUARTER_HOURS_PER_DAY,
    ANSAbility,
    AnsForecastEntry,
    Battery,
    ClearedReservation,
    Composite,
    Day,
    DayAheadBid,
    DayAheadParams,
    DayAheadPlan,
    Device,
    Distribution,
    ElectricityExport,
    ElectricityImport,
    EmpiricalPercentiles,
    ExpectedRevenue,
    GasImport,
    HealthInfo,
    HeatExport,
    LogNormal,
    LogNormalFromQuantiles,
    Market,
    MostProbableRealization,
    PlanDayAheadRequest,
    PlanReservationRequest,
    Profile,
    ReservationBid,
    ReservationParams,
    ReservationPlan,
    RunDetail,
    RunEndpoint,
    RunInfo,
    RunsPage,
    RunStatus,
    RunSummary,
    Schedule,
    ServiceCode,
    Site,
    Storage,
)

__all__ = [
    "__version__",
    # Client
    "API_KEY_PREFIX",
    "DEFAULT_TIMEOUT_SECONDS",
    "BusyRetry",
    "OperationalClient",
    # Errors
    "AuthenticationError",
    "BusyError",
    "CancelledError",
    "DayNotPlannableError",
    "IdempotencyConflictError",
    "InfeasibleError",
    "NotFoundError",
    "OperationalError",
    "OperationalTimeoutError",
    "RequestTooLargeError",
    "ServerError",
    "TransportError",
    "UnboundedError",
    "ValidationError",
    # Site
    "ANSAbility",
    "Battery",
    "Market",
    "Composite",
    "Storage",
    "Profile",
    "CHP",
    "Device",
    "ElectricityExport",
    "ElectricityImport",
    "GasImport",
    "HeatExport",
    "Site",
    # Day and forecast
    "AnsForecastEntry",
    "BLOCKS_PER_DAY",
    "Day",
    "Distribution",
    "EmpiricalPercentiles",
    "LogNormal",
    "LogNormalFromQuantiles",
    "QUARTER_HOURS_PER_DAY",
    "ServiceCode",
    # Reservation step
    "ExpectedRevenue",
    "MostProbableRealization",
    "PlanReservationRequest",
    "ReservationBid",
    "ReservationParams",
    "ReservationPlan",
    "RunInfo",
    # Day-ahead step
    "ClearedReservation",
    "DayAheadBid",
    "DayAheadParams",
    "DayAheadPlan",
    "PRICE_TAKER_BUY_EUR_PER_MWH",
    "PRICE_TAKER_SELL_EUR_PER_MWH",
    "PlanDayAheadRequest",
    "Schedule",
    # Health and runs
    "HealthInfo",
    "RunDetail",
    "RunEndpoint",
    "RunStatus",
    "RunSummary",
    "RunsPage",
]
